package model.enums;

public enum DataTableRowFormat {
    LOGEMENT, ADMIN, AGENT, OPERATEUR, CLIENT, MESSAGE, RESPONSABLE_VENTES, VENTE, VISITE, BANS, SIGNALS, LOCALITE, SIGNALER, ASSIGNER_REGION, APPROUVER_EMPLOYE, GELER_LOGEMENT, MODIFIER_VISITE, ETABLIR_RAPPORT, VERSEMENTS_FOR_VENTE, SUSPENDRE_EMPLOYE, RAPPORT, NOTIFICATIONS, BANNIR_CLIENT, PLAINTE;

}
