package model.enums;

public enum DataTableRowFormat {
    LOGEMENT,ADMIN,AGENT,OPERATEUR,CLIENT,MESSAGE,RESPONSABLE_VENTES,VENTE,VISITE,BANS,SIGNALS,LOCALITE,ASSIGNER_REGION
    // TODO: 2/18/2018
}
