package model.enums;

public enum DataTableRowFormat {
    LOGEMENT,ADMIN,AGENT,OPERATEUR,CLIENT,MESSAGE,RESPONSABLE_VENTES,VENTE,VISITE,BANS,SIGNALS,LOCALITE, SIGNALER, ASSIGNER_REGION,APPROUVER_EMPLOYE, SUSPENDRE_EMPLOYE
}
