package model.enums;

public enum TablePage {        // TODO: 2/18/2018

    LOGEMENTS, LOGEMENTS_FOR_USER, LOGEMENTS_VENDUS, FROZEN_LOGEMENTS, LOGEMENTS_NON_VENDUS,
    AGENTS, SUSPENDED_AGENTS,
    OPERATEURS, SUSPENDED_OPERATEURS,
    RESPONSABLES_VENTES, SUSPENDED_RESPONSABLES_VENTES,
    VISITES, REPORTED_VISITES, CANCELED_VISITES, USER_VISITES, PROGRAMMED_VISITES,
    ADMINS,
    LOCALITES,
    CLIENTS, CLIENTS_FOR_USER, BANNED_CLIENTS,
    MESSAGES, ADMINISTRATION_MESSAGES_FOR_USER, PASSED_VISITS, CLIENTS_MESSAGES_FOR_USER
}
