package model.enums;

public enum TablePage {

    LOGEMENTS, LOGEMENTS_FOR_USER, LOGEMENTS_VENDUS, FROZEN_LOGEMENTS, LOGEMENTS_NON_VENDUS, EMPLOYES,
    AGENTS, SUSPENDED_AGENTS,
    OPERATEURS, SUSPENDED_OPERATEURS,
    RESPONSABLES_VENTES, SUSPENDED_RESPONSABLES_VENTES,
    VISITES, REPORTED_VISITES, CANCELED_VISITES, AGENT_VISITES, PROGRAMMED_VISITES,
    ADMINS, NEW_MESSAGE, MY_CANCELED_VISITS,
    LOCALITES, PLAINTES, VENTES, CONFIRMED_VENTES, VENTES_EN_COURS,
    CLIENTS, CLIENTS_FOR_USER, BANNED_CLIENTS, MESSAGES_FOR_ADMIN, BANNIR_CLIENT,
    MESSAGES, ADMINISTRATION_MESSAGES_FOR_USER, PASSED_VISITS, ADMINISTRATION_MESSAGES_FOR_EMPLOYEES,
    CLIENTS_MESSAGES_FOR_USER, MODIFIER_PROFIL, CHANGER_MOT_DE_PASSE, LOGOUT, CLIENTS_FOR_AGENT, ASSIGNER_REGION,
    SIGNALEMENT, SIGNALER_CLIENT, APPROUVER_EMPLOYE, SUSPENDRE_EMPLOYE, SUSPENDRE_ADMIN, GELER_LOGEMENT, MODIFIER_VISITE, NOUVELLE_VENTE, VENTES_ANNULEES, VERSEMENTS_FOR_VENTE, VERSEMENTS_FOR_USER, ETABLIR_RAPPORT, AJOUTER_VERSEMENT, CLIENT_MY_VISITS, CLIENT_MY_NOTIFICATIONS, CLIENT_MES_VENTES_EN_COURS, RAPPORTS_LIST, CLIENT_MES_LOGEMENT_VISITES, EMPLOYEE_NOTIFICATIONS, MY_PASSED_VISITS, ANNULER_VENTE
}
